import os
import re
from pathlib import Path

filename = "../Driver.java"

JAVA_PACKAGE_NAME = "com.cs1331.drivers" 

os.makedirs(os.path.dirname(filename), exist_ok=True)

read_files = list(Path("../src/").rglob("*.java"))

for fi in read_files:
    print("Found " + str(fi))

with open(filename, "wb") as outfile:
    code_lines = []
    import_lines = []

    inject_path = None

    for f in read_files:
        with open(f, "rb") as infile:
            code_lines.append(("//AUTOGENERATED FROM " + infile.name + "\n").encode())
            
            for line in infile:
                line = str(line, 'UTF-8')
                line = line.replace("public class", "class")
                line = line.replace("public enum", "enum")
                line = line.replace("public @interface", "@interface")
                line = line.replace("public final", "final")
                line = line.replace("HW07Driver", "Driver")

                if inject_path != None:
                    regex = r"^(.*?)\""
                    match = re.search(regex, line).group(1).rstrip()

                    with open("../src/" + inject_path) as inject_file:
                        inject_lines = "".join(inject_file.readlines())
                        inject_lines = inject_lines.replace('\n', '\\n')

                        new_line = match + " \"" + inject_lines + "\\n\";"

                        code_lines.append(new_line.encode())

                    inject_path = None
                    continue

                if "@InjectData" in line:
                    regex = r'"(.*?)"'

                    match = re.findall(regex, line)[0]

                    inject_path = match
                    code_lines.append(("\t//AUTOMATICALLY EXTRACTED FROM " + match + "\n").encode())
                    continue

                if not line.strip() in import_lines:
                    if JAVA_PACKAGE_NAME in line:
                        continue


                    if line.startswith("import"):

                        import_lines.append(line.strip());
                        outfile.write(line.encode())

                        continue
                    else:
                        code_lines.append(line.encode())
                
            code_lines.append("\n".encode())

    outfile.writelines(code_lines)
